name: Static analysis
on: [ push, pull_request ]
jobs:
  job:
    runs-on: ubuntu-latest
    name: Static analysis

    steps:
      - uses: actions/checkout@v4
      - name: Run clang-tidy
        uses: HorstBaerbel/action-clang-tidy@1.2
        # These are optional (defaults displayed)
        with:
          scandir: '.'
          builddir: 'build'
          excludedirs: 'test'
          extensions: 'h,cc'
          cmakeoptions: ''